version: '3.8'

services:
  # Base de datos MySQL
  mysql-db:
    image: mysql:8.0
    container_name: support-tickets-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: support_tickets_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - support-tickets-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend API (Spring Boot)
  backend-api:
    image: santiagoarroyo/arroyo_santiago_leccion1:1.0
    container_name: support-tickets-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/support_tickets_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - support-tickets-network
    restart: on-failure

  # Frontend (Nginx)
  frontend-web:
    image: santiagoarroyo/front_examen:latest
    container_name: support-tickets-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-api
    networks:
      - support-tickets-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  support-tickets-network:
    driver: bridge
